#docker-compose 버전 지정
version: '2'
#docker-compose의 경우 docker 컨테이너로 수행될 서비스들은 services 하위에 기술
services:
  #서비스 이름. service 하위에 작성하면 해당 이름으로 동작
  zookeeper:
    #도커 이미지
    image: wurstmeister/zookeeper
    container_name: zookeeper
    #외부포트:컨테이너내부포트
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    #외부포트:컨테이너내부포트
    ports:
      - "9092:9092"
    #kafka 브로터를 위한 환경 변수 지정
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      #kafka가 zookeeper에 커넥션하기 위한 대상을 지정
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock